### ISSUE TITLE
Could you please add an sdist on PyPI, and git tags? :)

### ISSUE THREAD

**Issue by hoechenberger** [drbenvincent/badapted#4]
This is the same request as in https://github.com/drbenvincent/darc_toolbox/issues/84 :) Would be great if you could  find some time to look into this.

Thank you!

**Comment by drbenvincent** [comment]
Will do. Should be able to get this resolved (for both repo's) in the next day or so

**Comment by drbenvincent** [comment]
This is now mostly resolved. I've updated setup.py and included MANIFEST.in. I've also made a GitHub release with the version tagged https://github.com/drbenvincent/badapted/releases/tag/0.0.3

Have also tried the improved procedure to build and upload to PyPI... https://pypi.org/project/badapted/ 

Would be gratefully if you could take a look and see if this has worked as expected? If so, then I'll do the same for the darc_toolbox https://github.com/drbenvincent/darc_toolbox/issues/84

**Comment by hoechenberger** [comment]
@drbenvincent All seems to be in order! Thanks for your effort!
